{
 "title": "Chainlink",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current Head",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "head_tracker_current_head" }
   ]
  },
  {
   "title": "Eth-Balance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "eth_balance" }
   ]
  },
  {
   "title": "Heads dropped",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "head_tracker_num_heads_dropped{job=~\"chainlink_p.*\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Head Tracker Heads in Queue",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "head_tracker_heads_in_queue{job=~\"chainlink_p.*\"}"
    }
   ]
  },
  {
   "title": "Head Tracker Callback Execution Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "head_tracker_callback_execution_duration"
    }
   ]
  },
  {
   "title": "Job Subscriptions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "job_subscriber_subscriptions{job=~\"chainlink_p.*\"}"
    }
   ]
  },
  {
   "title": "New heads per minute",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(head_tracker_heads_received{job=~\"chainlink_p.*\"}[1m])*60"
    }
   ]
  },
  {
   "title": "Run Queue Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "run_queue_queue_size" }
   ]
  },
  {
   "title": "Current Head increase",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(head_tracker_current_head{job=~\"chainlink_p.*\"}[1m])*60",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "New heads per minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 5, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(head_tracker_heads_received{job=~\"chainlink_p.*\"}[1m])*60"
    }
   ]
  },
  {
   "title": "Container uptime",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "up" }
   ]
  },
  {
   "title": "Gas Price",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gas_updater_set_gas_price" }
   ]
  },
  {
   "title": "Gas Price Percentiles",
   "type": "graph",
   "gridPos": { "h": 12, "w": 11, "x": 9, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gas_updater_all_gas_percetiles{percentile!=\"100%\",job=~\"chainlink_p.*\"}/1000000000",
     "legendFormat": "{{percentile}}"
    }
   ]
  },
  {
   "title": "Head Tracker Heads in Queue",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "head_tracker_heads_in_queue{job=~\"chainlink_p.*\"}"
    }
   ]
  },
  {
   "title": "Eth Balance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "eth_balance" }
   ]
  },
  {
   "title": "Head Tracker eth connection ERROR",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "head_tracker_eth_connection_errors"
    }
   ]
  }
 ]
}